export const ALGO = "ALGO";
export const TOGGLE_COLOR_MODE = "TOGGLE_COLOR_MODE";
export const SIDEBAR_PROVIDER = "SIDEBAR_PROVIDER";
export const WINDOW_SIZE = "WINDOW_SIZE";
export const IS_COLLAPSED = "IS_COLLAPSED";